name: CI
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: [17, 21, 25]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.jdk_version }}
      - uses: sbt/setup-sbt@v1
      - name: Set Env
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Build
        run: sbt -v +compile Debian/packageBin
      - name: Upload assets to Github
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')  && matrix.jdk_version == 21 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          sbt Universal/packageBin
          gh release create --generate-notes "$VERSION" "target/Cashy_${VERSION}_all.deb" "target/universal/cashy-$VERSION.zip"
