name: CI
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: [8, 11, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk_version }}
      - name: Set Env
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Build
        run: sbt -v +compile Debian/packageBin
      - name: Upload assets to Github
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')  && matrix.jdk_version == 17 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          sbt Universal/packageBin
          args=$(printf -- "-a %q " target/*.deb)
          hub release create -m "$VERSION" -a "target/Cashy_${VERSION}_all.deb" -a "target/universal/cashy-$VERSION.zip" "$VERSION"
